### PR TITLE
Add IRC backend

### PR DESCRIPTION
**Pull request by waynesun09**
- Add irc utils module
- Implement the irc send_message api
- Update the config file with irc part
- Update the helm chart with irc config

This resolves https://github.com/waynesun09/notify-service/issues/3

### CODE REVIEW

**Comment by waynesun09** [comment]
@abraverm could you help check?
Thanks

**Review by abraverm — COMMENTED** [review]
looks solid to me but I don't know if and how error are being handled. for example 
I'm not sure what would be the final value for  `settings.IRC_TARGET` ( chart/values.yaml (line 87) -> chart/templates/deployment.yaml  (line 138) -> ... -> None\ ""\?) and I don't know if irc client will fail gracefully if no target is specified or what will happen. Same goes regarding authentication failure.

Also, SSL might be an issue when some internal certificate is used and not properly installed on the system that is running IRC.

Last,  I noticed the `accessMode` chanaged to  `ReadWriteOnce` - is there a particular reason related to IRC?

**Comment by waynesun09** [comment]
For the error handling, I expect the connection error to be raised and expose to client when send message fail. But as I just checked, with recent update put the connection into future task, the exception did not return to the api call, which I need fix.

The IRC_TARGET could be a user name or a channel name start with '#', I will add comment on that.

SSL is not an issue in my current test, the irc client_aio module did not expose the ssl and ipv6 options though the AioFactory supposed to support them now. So for the ssl and ipv6 connection I will raise a new issue.

The accessMode update is not related to irc, I should have put it in another commit.

**Comment by abraverm** [comment]
What if a user doesn't specify IRC_TARGET?

**Comment by waynesun09** [comment]
IRC_TARGET default to None in settings, and the send_message function accept user specify target as option, if user did not specify target it will fallback to default setting, and if default is also None it will raise exception.

Currently the target is a required option in the send_message api, but it's possible for a service to have the target pre-configured.

**Comment by abraverm** [comment]
I would recommend to catch all exceptions, but that is out of scope for this PR.

**Comment by waynesun09** [comment]
Updated with caught the connection exception and return to client.

**Pull request merged**
